### ISSUE TITLE
Writing to CSV instead of XLSX

### ISSUE THREAD

**Issue by jrrrp** [willlam98/ObjectPropertiesInformationExtraction#1]
https://github.com/willlam98/ObjectPropertiesInformationExtraction/blob/4e3bd464c1b2e258af56a8987ede1c83600fce8a/script.py#L82-L84

Not a big issue, but I was wondering why the choice was made to write to xlsx, when csv is more portable and still supported by excel?

**Comment by wiwiamlam** [comment]
Because I assume that most of the people use MS excel for labelling, and if you may know Excel seems to have lots of problem to reading/writing .csv file (e.g. the formatting). So I think it is safer to do the labelling job in .xlsx and then convert to .csv

**Comment by jrrrp** [comment]
Ah, I didn't know that there were such issues. Understood!
